# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ResponseModel")

model.instance <- ResponseModel$new()

test_that("hits", {
  # tests for the property `hits` (array[object])

  # uncomment below to test the property 
  #expect_equal(model.instance$`hits`, "EXPECTED_RESULT")
})

test_that("facets", {
  # tests for the property `facets` (array[object])

  # uncomment below to test the property 
  #expect_equal(model.instance$`facets`, "EXPECTED_RESULT")
})

test_that("stats", {
  # tests for the property `stats` (ResponseStats)

  # uncomment below to test the property 
  #expect_equal(model.instance$`stats`, "EXPECTED_RESULT")
})

test_that("success", {
  # tests for the property `success` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`success`, "EXPECTED_RESULT")
})

test_that("cursor", {
  # tests for the property `cursor` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`cursor`, "EXPECTED_RESULT")
})

