# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ResponseStats")

model.instance <- ResponseStats$new()

test_that("total", {
  # tests for the property `total` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`total`, "EXPECTED_RESULT")
})

test_that("took", {
  # tests for the property `took` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`took`, "EXPECTED_RESULT")
})

