# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SRAApi")

api.instance <- SRAApi$new()

test_that("ExperimentByAccessionSraExperimentsAccessionGet", {
  # tests for ExperimentByAccessionSraExperimentsAccessionGet
  # base path: http://localhost
  # Experiment By Accession
  # @param accession character An accession for lookup
  # @param include.fields array[character] Fields to include in results. The default is to all fields (*) (optional)
  # @param exclude.fields array[character] Fields to exclude from results. The default is to not exclude any fields.  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ExperimentsForSampleSraSamplesAccessionExperimentsGet", {
  # tests for ExperimentsForSampleSraSamplesAccessionExperimentsGet
  # base path: http://localhost
  # Experiments For Sample
  # @param accession character An accession for lookup
  # @param include.fields array[character] Fields to include in results. The default is to all fields (*) (optional)
  # @param exclude.fields array[character] Fields to exclude from results. The default is to not exclude any fields.  (optional)
  # @param size integer  (optional)
  # @param cursor character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ExperimentsForStudySraStudiesAccessionExperimentsGet", {
  # tests for ExperimentsForStudySraStudiesAccessionExperimentsGet
  # base path: http://localhost
  # Experiments For Study
  # @param accession character An accession for lookup
  # @param include.fields array[character] Fields to include in results. The default is to all fields (*) (optional)
  # @param exclude.fields array[character] Fields to exclude from results. The default is to not exclude any fields.  (optional)
  # @param size integer  (optional)
  # @param cursor character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ExperimentsSraExperimentsGet", {
  # tests for ExperimentsSraExperimentsGet
  # base path: http://localhost
  # Experiments
  # @param q character The query, using [lucene query syntax](https://lucene.apache.org/core/3_6_0/queryparsersyntax.html) (optional)
  # @param size integer  (optional)
  # @param cursor character The cursor is used to scroll through results. For a query with more results than `size`, the result will include `cursor` in the result json. Use that value here and re-issue the query. The next set or results will be returned. When no more results are available, the `cursor` will again be empty in the result json. (optional)
  # @param facet.size integer The maximum number of records returned for each facet. This has no effect unless one or more facets are specified. (optional)
  # @param include.fields array[character] Fields to include in results. The default is to all fields (*) (optional)
  # @param exclude.fields array[character] Fields to exclude from results. The default is to not exclude any fields.  (optional)
  # @param facets array[character] A list of strings identifying fields for faceted search results. Simple term faceting is used here, meaning that fields that are short text and repeated across records will be binned and counted. (optional)
  # @return [ResponseModel]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MappingSraFieldsEntityGet", {
  # tests for MappingSraFieldsEntityGet
  # base path: http://localhost
  # Mapping
  # @param entity character 
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RunByAccessionSraRunsAccessionGet", {
  # tests for RunByAccessionSraRunsAccessionGet
  # base path: http://localhost
  # Run By Accession
  # @param accession character An accession for lookup
  # @param include.fields array[character] Fields to include in results. The default is to all fields (*) (optional)
  # @param exclude.fields array[character] Fields to exclude from results. The default is to not exclude any fields.  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RunsForExperimentSraExperimentsAccessionRunsGet", {
  # tests for RunsForExperimentSraExperimentsAccessionRunsGet
  # base path: http://localhost
  # Runs For Experiment
  # @param accession character An accession for lookup
  # @param include.fields array[character] Fields to include in results. The default is to all fields (*) (optional)
  # @param exclude.fields array[character] Fields to exclude from results. The default is to not exclude any fields.  (optional)
  # @param size integer  (optional)
  # @param cursor character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RunsForSampleSraSamplesAccessionRunsGet", {
  # tests for RunsForSampleSraSamplesAccessionRunsGet
  # base path: http://localhost
  # Runs For Sample
  # @param accession character An accession for lookup
  # @param include.fields array[character] Fields to include in results. The default is to all fields (*) (optional)
  # @param exclude.fields array[character] Fields to exclude from results. The default is to not exclude any fields.  (optional)
  # @param size integer  (optional)
  # @param cursor character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RunsForStudySraStudiesAccessionRunsGet", {
  # tests for RunsForStudySraStudiesAccessionRunsGet
  # base path: http://localhost
  # Runs For Study
  # @param accession character An accession for lookup
  # @param include.fields array[character] Fields to include in results. The default is to all fields (*) (optional)
  # @param exclude.fields array[character] Fields to exclude from results. The default is to not exclude any fields.  (optional)
  # @param size integer  (optional)
  # @param cursor character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RunsSraRunsGet", {
  # tests for RunsSraRunsGet
  # base path: http://localhost
  # Runs
  # @param q character The query, using [lucene query syntax](https://lucene.apache.org/core/3_6_0/queryparsersyntax.html) (optional)
  # @param size integer  (optional)
  # @param cursor character The cursor is used to scroll through results. For a query with more results than `size`, the result will include `cursor` in the result json. Use that value here and re-issue the query. The next set or results will be returned. When no more results are available, the `cursor` will again be empty in the result json. (optional)
  # @param facet.size integer The maximum number of records returned for each facet. This has no effect unless one or more facets are specified. (optional)
  # @param include.fields array[character] Fields to include in results. The default is to all fields (*) (optional)
  # @param exclude.fields array[character] Fields to exclude from results. The default is to not exclude any fields.  (optional)
  # @param facets array[character] A list of strings identifying fields for faceted search results. Simple term faceting is used here, meaning that fields that are short text and repeated across records will be binned and counted. (optional)
  # @return [ResponseModel]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SampleByAccessionSraSamplesAccessionGet", {
  # tests for SampleByAccessionSraSamplesAccessionGet
  # base path: http://localhost
  # Sample By Accession
  # @param accession character An accession for lookup
  # @param include.fields array[character] Fields to include in results. The default is to all fields (*) (optional)
  # @param exclude.fields array[character] Fields to exclude from results. The default is to not exclude any fields.  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SamplesForStudySraStudiesAccessionSamplesGet", {
  # tests for SamplesForStudySraStudiesAccessionSamplesGet
  # base path: http://localhost
  # Samples For Study
  # @param accession character An accession for lookup
  # @param include.fields array[character] Fields to include in results. The default is to all fields (*) (optional)
  # @param exclude.fields array[character] Fields to exclude from results. The default is to not exclude any fields.  (optional)
  # @param size integer  (optional)
  # @param cursor character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SamplesSraSamplesGet", {
  # tests for SamplesSraSamplesGet
  # base path: http://localhost
  # Samples
  # @param q character The query, using [lucene query syntax](https://lucene.apache.org/core/3_6_0/queryparsersyntax.html) (optional)
  # @param size integer  (optional)
  # @param cursor character The cursor is used to scroll through results. For a query with more results than `size`, the result will include `cursor` in the result json. Use that value here and re-issue the query. The next set or results will be returned. When no more results are available, the `cursor` will again be empty in the result json. (optional)
  # @param facet.size integer The maximum number of records returned for each facet. This has no effect unless one or more facets are specified. (optional)
  # @param include.fields array[character] Fields to include in results. The default is to all fields (*) (optional)
  # @param exclude.fields array[character] Fields to exclude from results. The default is to not exclude any fields.  (optional)
  # @param facets array[character] A list of strings identifying fields for faceted search results. Simple term faceting is used here, meaning that fields that are short text and repeated across records will be binned and counted. (optional)
  # @return [ResponseModel]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("StudiesSraStudiesGet", {
  # tests for StudiesSraStudiesGet
  # base path: http://localhost
  # Studies
  # @param q character The query, using [lucene query syntax](https://lucene.apache.org/core/3_6_0/queryparsersyntax.html) (optional)
  # @param size integer  (optional)
  # @param cursor character The cursor is used to scroll through results. For a query with more results than `size`, the result will include `cursor` in the result json. Use that value here and re-issue the query. The next set or results will be returned. When no more results are available, the `cursor` will again be empty in the result json. (optional)
  # @param facet.size integer The maximum number of records returned for each facet. This has no effect unless one or more facets are specified. (optional)
  # @param include.fields array[character] Fields to include in results. The default is to all fields (*) (optional)
  # @param exclude.fields array[character] Fields to exclude from results. The default is to not exclude any fields.  (optional)
  # @param facets array[character] A list of strings identifying fields for faceted search results. Simple term faceting is used here, meaning that fields that are short text and repeated across records will be binned and counted. (optional)
  # @return [ResponseModel]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("StudyByAccessionSraStudiesAccessionGet", {
  # tests for StudyByAccessionSraStudiesAccessionGet
  # base path: http://localhost
  # Study By Accession
  # @param accession character An accession for lookup
  # @param include.fields array[character] Fields to include in results. The default is to all fields (*) (optional)
  # @param exclude.fields array[character] Fields to exclude from results. The default is to not exclude any fields.  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

