# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DefaultApi")

api.instance <- DefaultApi$new()

test_that("FacetsByIndexFacetsEntityGet", {
  # tests for FacetsByIndexFacetsEntityGet
  # base path: http://localhost
  # Facets By Index
  # Return the available facet fields for an entity
  # @param entity AnyType 
  # @return [array[character]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

